import { FileUp, Info, LoaderCircle, Send, Sparkles, XCircle } from 'lucide-react'
import { useRef, useState } from 'react'
import { getApiError } from '../../api/client'

export default function CopilotPanel({ messages, onSend, onUpload, loading = false, error = '' }) {
  const [value, setValue] = useState('')
  const fileRef = useRef(null)
  const submit = async (event) => { event.preventDefault(); const message = value.trim(); if (!message || loading) return; setValue(''); await onSend(message) }
  const upload = async (event) => { const file = event.target.files?.[0]; if (file) await onUpload(file); event.target.value = '' }
  return <section className="flex min-h-[620px] flex-col overflow-hidden rounded-md border border-slate-200 bg-white text-[#172033] shadow-[0_2px_8px_rgba(25,35,55,0.06)]">
    <div className="flex items-center justify-between border-b border-slate-200 px-4 py-4"><div className="flex items-center gap-3"><div className="grid h-8 w-8 place-items-center rounded-md bg-blue-50 text-[#2d6cdf]"><Sparkles size={17} /></div><div><h2 className="text-sm font-semibold">AI Complaint Intake Assistant</h2></div></div><span className="rounded bg-blue-50 px-1.5 py-0.5 text-[9px] font-bold text-[#2d6cdf]">BETA</span></div>
    <div className="flex-1 space-y-3 overflow-y-auto p-4"><div className="rounded-md border border-dashed border-slate-300 px-4 py-5 text-center text-xs text-slate-500"><FileUp className="mx-auto mb-2 text-slate-400" size={21} /><span>Drag &amp; drop complaint document here<br /><button type="button" onClick={() => fileRef.current?.click()} className="font-semibold text-[#2d6cdf]">or click to browse</button></span></div><div className="flex items-center gap-3 text-[10px] text-slate-400"><span className="h-px flex-1 bg-slate-200" />OR<span className="h-px flex-1 bg-slate-200" /></div><button type="button" onClick={() => document.querySelector('#copilot-message')?.focus()} className="w-full rounded-md border border-slate-200 py-2 text-xs text-slate-600">▤ &nbsp; Paste Complaint Text / Email</button><div className="flex gap-2 rounded-md border border-green-200 bg-green-50 p-2 text-[10px] leading-4 text-green-700"><Info size={13} className="shrink-0" />Supported formats: PDF, DOCX, TXT, EML<br />Max file size: 10MB</div><div className="border-t border-slate-200 pt-4"><div className="mb-2 flex justify-between text-[10px] font-bold uppercase tracking-wider text-slate-500"><span>Extraction progress</span><span>10%</span></div><div className="h-3 overflow-hidden rounded-full bg-slate-100"><div className="h-full w-[18%] rounded-full bg-[#2d6cdf]" /></div><p className="mt-2 text-[10px] leading-4 text-slate-600">Analyzing document content and extracting key details...<br />Please wait, this may take a few moments.</p></div><div className="border-t border-slate-200 pt-3"><p className="mb-2 text-[10px] font-bold uppercase tracking-wider text-slate-500">AI assistant</p>{messages.map((message, index) => <div key={`${message.role}-${index}`} className={`mb-2 rounded-md px-3 py-2 text-xs leading-4 ${message.role === 'user' ? 'bg-blue-50 text-slate-700' : 'bg-blue-50 text-slate-600'}`}>{message.content}</div>)}{loading && <div className="flex items-center gap-2 text-xs text-slate-500"><LoaderCircle size={14} className="animate-spin" /> Reviewing the complaint...</div>}{error && <div className="flex gap-2 rounded-md border border-red-200 bg-red-50 p-2 text-xs text-red-700"><XCircle size={14} />{getApiError({ message: error }, error)}</div>}</div></div>
    <div className="border-t border-slate-200 p-3"><form onSubmit={submit} className="flex items-end gap-2 rounded-md border border-slate-200 p-1"><textarea id="copilot-message" value={value} onChange={(event) => setValue(event.target.value)} rows={1} maxLength={10000} placeholder="Ask me anything about this complaint..." className="min-h-8 flex-1 resize-none px-2 py-1 text-xs outline-none placeholder:text-slate-400" /><button type="submit" disabled={loading || !value.trim()} className="grid h-8 w-8 shrink-0 place-items-center rounded bg-[#2d6cdf] text-white disabled:opacity-40" title="Send message" aria-label="Send message"><Send size={15} /></button></form><input ref={fileRef} type="file" accept="application/pdf,.pdf" onChange={upload} className="hidden" /><p className="mt-2 text-center text-[9px] text-slate-400">AI responses may contain errors. Please verify information.</p></div>
  </section>
}
