import { FileUp, MessageSquare, Pencil, Plus, ShieldAlert, Trash2 } from 'lucide-react'

const iconFor = { complaint_created: Plus, complaint_updated: Pencil, complaint_deleted: Trash2, ai_extraction: SparkIcon, ai_edit: MessageSquare, risk_assessment_created: ShieldAlert, risk_assessment_updated: ShieldAlert, document_uploaded: FileUp, complaint_status_changed: Pencil }
function SparkIcon(props) { return <span {...props}>✦</span> }
const labels = { complaint_created: 'Complaint created', complaint_updated: 'Complaint updated', complaint_deleted: 'Complaint deleted', ai_extraction: 'AI extracted complaint', ai_edit: 'AI edited complaint', risk_assessment_created: 'Risk assessment created', risk_assessment_updated: 'Risk assessment updated', document_uploaded: 'Document uploaded', complaint_status_changed: 'Status changed' }

export default function AuditTimeline({ events = [] }) {
  return <section className="rounded-2xl border border-line bg-white p-5 shadow-panel sm:p-7"><div className="mb-6"><p className="mb-1 text-xs font-bold uppercase tracking-[0.16em] text-coral">Traceability</p><h2 className="font-display text-xl font-bold text-ink">Audit history</h2></div>{events.length === 0 ? <p className="text-sm text-slate-500">No audit events yet.</p> : <div className="space-y-5">{events.map((event, index) => { const Icon = iconFor[event.action] || MessageSquare; return <div key={event.id || index} className="relative flex gap-3">{index < events.length - 1 && <span className="absolute left-[15px] top-8 h-[calc(100%+8px)] w-px bg-line" />}<span className="relative grid h-8 w-8 shrink-0 place-items-center rounded-xl bg-mint text-fern"><Icon size={15} /></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center justify-between gap-2"><p className="text-sm font-bold text-ink">{labels[event.action] || event.action}</p><time className="text-xs text-slate-400">{new Date(event.created_at).toLocaleString()}</time></div>{event.new_data?.file_size && <p className="mt-1 text-xs text-slate-500">PDF · {(event.new_data.file_size / 1024).toFixed(1)} KB</p>}</div></div> })}</div>}</section>
}
