import { ArrowLeft, CheckCircle2, Save, Trash2 } from 'lucide-react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { useEffect, useState } from 'react'
import { getApiError } from '../api/client'
import { editComplaintWithAI } from '../api/chatApi'
import { extractDocument, getAuditHistory } from '../api/documentApi'
import { deleteComplaint, updateComplaint } from '../api/complaintApi'
import AppShell, { PageHeading, PrimaryButton } from '../components/dashboard/AppShell'
import ComplaintStatePanel from '../components/complaint/ComplaintStatePanel'
import CopilotPanel from '../components/copilot/CopilotPanel'
import AuditTimeline from '../components/audit/AuditTimeline'
import { useComplaint } from '../hooks/useComplaint'

const opening = [{ role: 'assistant', content: 'This is the current structured complaint. Tell me exactly what you want to change, and I will preserve everything else.' }]
export default function ComplaintDetailsPage() {
  const { id } = useParams(); const navigate = useNavigate(); const { complaint, setComplaint, loading: complaintLoading, error: loadError, loadComplaint } = useComplaint(); const [risk, setRisk] = useState(null); const [audit, setAudit] = useState([]); const [messages, setMessages] = useState(opening); const [loading, setLoading] = useState(false); const [saveLoading, setSaveLoading] = useState(false); const [deleteLoading, setDeleteLoading] = useState(false); const [status, setStatus] = useState('draft'); const [success, setSuccess] = useState(''); const [error, setError] = useState('')
  useEffect(() => { Promise.all([loadComplaint(id), getAuditHistory(id)]).then(([data, events]) => { setRisk(data.risk_assessment); setStatus(data.status); setAudit(events) }).catch(() => {}) }, [id, loadComplaint])
  const send = async (message) => { setLoading(true); setError(''); setMessages((items) => [...items, { role: 'user', content: message }]); try { const data = await editComplaintWithAI(id, message); setComplaint(data.complaint); setRisk(data.risk_assessment); setAudit(await getAuditHistory(id)); setMessages((items) => [...items, { role: 'assistant', content: 'Updated. The structured record and risk assessment now reflect that instruction.' }]) } catch (requestError) { setError(getApiError(requestError, 'The copilot could not update this complaint.')); setMessages((items) => [...items, { role: 'assistant', content: 'I could not apply that change. Please try again.' }]) } finally { setLoading(false) } }
  const upload = async (file) => { setLoading(true); setError(''); try { const data = await extractDocument(id, file); setComplaint(data.complaint); setRisk(data.risk_assessment); setAudit(await getAuditHistory(id)); setMessages((items) => [...items, { role: 'assistant', content: 'The PDF was saved and its extracted complaint information has been applied.' }]) } catch (requestError) { setError(getApiError(requestError, 'The PDF could not be processed.')); } finally { setLoading(false) } }
  const saveStatus = async () => { setSaveLoading(true); setSuccess(''); setError(''); try { const data = await updateComplaint(id, { status }); setComplaint(data); setRisk(data.risk_assessment); setAudit(await getAuditHistory(id)); setSuccess('Complaint status saved.') } catch (requestError) { setError(getApiError(requestError, 'The complaint could not be updated.')) } finally { setSaveLoading(false) } }
  const remove = async () => { if (!window.confirm('Delete this complaint? This cannot be undone.')) return; setDeleteLoading(true); setError(''); try { await deleteComplaint(id); navigate('/dashboard') } catch (requestError) { setError(getApiError(requestError, 'The complaint could not be deleted.')); setDeleteLoading(false) } }
  return <AppShell><Link to="/dashboard" className="mb-6 inline-flex items-center gap-2 text-sm font-bold text-slate-500 hover:text-ink"><ArrowLeft size={16} /> Back to complaint desk</Link><PageHeading kicker="Complaint record" title={complaint?.product_name || 'Complaint details'} description={complaint?.status ? `${complaint.status.replace('_', ' ')} · Updated by AI-assisted workflow` : 'Loading complaint record'} action={<div className="flex flex-wrap items-center gap-2"><select aria-label="Complaint status" value={status} onChange={(event) => setStatus(event.target.value)} disabled={!complaint || saveLoading || deleteLoading} className="rounded-xl border border-line bg-white px-3 py-2.5 text-sm font-semibold capitalize text-ink"><option value="draft">Draft</option><option value="submitted">Submitted</option><option value="under_review">Under review</option><option value="resolved">Resolved</option><option value="closed">Closed</option></select><PrimaryButton onClick={saveStatus} disabled={!complaint || saveLoading || deleteLoading}><Save size={16} /> {saveLoading ? 'Saving...' : 'Save status'}</PrimaryButton><PrimaryButton onClick={remove} disabled={deleteLoading || saveLoading} className="bg-white !text-coral ring-1 ring-coral/30 hover:!bg-coral hover:!text-white"><Trash2 size={16} /> {deleteLoading ? 'Deleting...' : 'Delete'}</PrimaryButton></div>} />{loadError && <div className="mb-5 rounded-xl bg-red-50 px-4 py-3 text-sm text-red-700">{loadError}</div>}{error && <div className="mb-5 rounded-xl bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}{success && <div className="mb-5 flex items-center gap-2 rounded-xl bg-mint/60 px-4 py-3 text-sm font-semibold text-fern"><CheckCircle2 size={17} /> {success}</div>}{complaintLoading && !complaint ? <div className="rounded-2xl border border-line bg-white p-12 text-center text-sm text-slate-500">Loading complaint...</div> : <><div className="grid items-start gap-6 xl:grid-cols-[1.1fr_0.9fr]"><ComplaintStatePanel complaint={complaint} risk={risk} /><CopilotPanel messages={messages} onSend={send} onUpload={upload} loading={loading} error="" /></div><div className="mt-6"><AuditTimeline events={audit} /></div></>}</AppShell>
}
